export const GET_ERRORS = "GET_ERRORS";
export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";

// Business
export const SET_CURRENT_BUSINESS = "SET_CURRENT_BUSINESS";
export const REGISTER_BUSINESS_SUCCESS = "REGISTER_BUSINESS_SUCCESS";
export const REGISTER_BUSINESS_FAIL = "REGISTER_BUSINESS_FAIL";
export const BUSINESS_LOADED = "BUSINESS_LOADED";
export const LOGIN_BUSINESS_SUCCESS = "LOGIN_BUSINESS_SUCCESS";
export const LOGIN_BUSINESS_FAIL = "LOGIN_BUSINESS_FAIL";
export const BUSINESS_ACCOUNT_DELETED = "BUSINESS_ACCOUNT_DELETED";
export const LOGOUT_BUSINESS = "LOGOUT_BUSINESS";
export const AUTH_ERROR_BUSINESS = "AUTH_ERROR_BUSINESS";
export const CLEAR_PROFILE_BUSINESS = "AUTH_ERROR_BUSINESS";

//Business profile
export const GET_PROFILE_BUSINESS = "GET_PROFILE_BUSINESS";
export const PROFILE_ERROR_BUSINESS = "PROFILE_ERROR_BUSINESS";
export const UPDATE_PROFILE_BUSINESS = "UPDATE_PROFILE_BUSINESS";
export const ACCOUNT_DELETED_BUSINESS = "ACCOUNT_DELETED_BUSINESS";
export const AVAILABILITY = "AVAILABILITY";
export const SERVICES = "SERVICES";

// User
export const SEARCH_ZIP = "SEARCH_ZIP";
export const SEARCH_CITY = "SEARCH_CITY";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_BUSINESS_INFO_BY_ID = "SEARCH_BUSINESS_INFO_BY_ID";
export const CHECK_TIME_SLOTS = "CHECK_TIME_SLOTS";
export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const MY_APPOINTMENT = "MY_APPOINTMENT";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";

export const GET_PROFILE = "GET_PROFILE";
export const GET_AVAILABILITY = "GET_AVAILABILITY";
export const GET_PROFILES = "GET_PROFILES";
export const GET_REPOS = "GET_REPOS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
